#!/usr/bin/env bash
# BAW Installer — one-command setup
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/cornreform/baw-agent-platform/main/install.sh | bash
#   bash install.sh
#
# Supports: Bash, Zsh, Fish (auto-detected)

set -e

BAW_REPO="https://github.com/cornreform/baw-agent-platform.git"
BAW_DIR="$HOME/baw"
BAW_BIN_DIR="$HOME/.local/bin"
BAW_BIN="$BAW_BIN_DIR/baw"
PYTHON=""
SHELL_CONFIG=""

# ── Colours ──
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║     BAW — Black And White Agent      ║"
echo "  ║         One-Command Installer         ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${NC}"

# ── Find Python ──
for cmd in python3.12 python3.11 python3; do
    if command -v "$cmd" &>/dev/null; then
        PYTHON="$cmd"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo -e "${RED}❌ Python 3.11+ not found.${NC}"
    echo "   Install it first:"
    echo "   macOS: brew install python@3.12"
    echo "   Linux: sudo apt install python3.12  (or your distro's equivalent)"
    exit 1
fi

echo -e "${GREEN}✅${NC} Python: $($PYTHON --version 2>&1)"

# ── Find Git ──
if ! command -v git &>/dev/null; then
    echo -e "${RED}❌ Git not found. Install it first.${NC}"
    exit 1
fi
echo -e "${GREEN}✅${NC} Git: $(git --version 2>&1)"

# ── Install pip dependencies ──
echo ""
echo -e "${CYAN}📦 Installing Python dependencies...${NC}"

# Try to detect if --break-system-packages is needed (PEP 668)
PIP_ARGS=""
if $PYTHON -m pip install --help 2>&1 | grep -q "break-system-packages"; then
    # Check if we'd hit PEP 668
    if $PYTHON -c "import sysconfig; import os; print(os.path.join(sysconfig.get_path('purelib'), 'EXTERNALLY-MANAGED'))" 2>/dev/null | xargs test -f 2>/dev/null; then
        PIP_ARGS="--break-system-packages"
        echo -e "  ${YELLOW}(detected externally-managed Python — using --break-system-packages)${NC}"
    fi
fi

$PYTHON -m pip install $PIP_ARGS pyyaml httpx duckduckgo-search croniter 2>&1 | tail -2
echo -e "${GREEN}✅${NC} Dependencies installed"

# ── Clone or update repo ──
echo ""
echo -e "${CYAN}📁 Setting up BAW repo...${NC}"
if [ -d "$BAW_DIR" ]; then
    echo "   BAW already exists at $BAW_DIR — pulling latest..."
    cd "$BAW_DIR" && git pull
else
    git clone "$BAW_REPO" "$BAW_DIR"
fi
echo -e "${GREEN}✅${NC} BAW repo ready at $BAW_DIR"

# ── Create CLI wrapper ──
mkdir -p "$BAW_BIN_DIR"
cat > "$BAW_BIN" << WRAPPER
#!/usr/bin/env bash
# BAW CLI wrapper — auto-generated by install.sh
cd "\$HOME/baw" && exec $PYTHON "\$HOME/baw/baw" "\$@"
WRAPPER
chmod +x "$BAW_BIN"
echo -e "${GREEN}✅${NC} CLI wrapper: $BAW_BIN"

# ── Detect shell and suggest PATH setup ──
echo ""
echo -e "${CYAN}🔧 Shell PATH setup...${NC}"

# Find the user's actual shell
SHELL_NAME="$(basename "$SHELL" 2>/dev/null || echo "bash")"
case "$SHELL_NAME" in
    zsh)
        SHELL_CONFIG="$HOME/.zshrc"
        PATH_CMD='export PATH="$HOME/.local/bin:$PATH"'
        ;;
    bash)
        SHELL_CONFIG="$HOME/.bashrc"
        PATH_CMD='export PATH="$HOME/.local/bin:$PATH"'
        ;;
    fish)
        SHELL_CONFIG="$HOME/.config/fish/config.fish"
        PATH_CMD='fish_add_path "$HOME/.local/bin"'
        ;;
    *)
        SHELL_CONFIG="$HOME/.profile"
        PATH_CMD='export PATH="$HOME/.local/bin:$PATH"'
        ;;
esac

if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
    echo -e "${GREEN}✅${NC} ~/.local/bin already in PATH"
else
    echo -e "  ${YELLOW}⚠️  ~/.local/bin is NOT in your PATH${NC}"
    echo ""
    echo "   Add it to your shell config by running:"
    echo ""
    echo -e "     ${BOLD}echo '$PATH_CMD' >> $SHELL_CONFIG${NC}"
    echo -e "     ${BOLD}source $SHELL_CONFIG${NC}"
    echo ""
    echo "   Or just run this to add it now:"
    echo ""
    echo -e "     ${BOLD}$PATH_CMD${NC}"
    echo ""
fi

# ── Verify installation ──
echo ""
echo -e "${CYAN}🔍 Verifying installation...${NC}"
if [ -f "$BAW_BIN" ] && [ -x "$BAW_BIN" ]; then
    echo -e "${GREEN}✅${NC} CLI wrapper executable"
fi
if [ -d "$BAW_DIR/baw" ]; then
    echo -e "${GREEN}✅${NC} BAW source files present"
fi
if [ -f "$BAW_DIR/requirements.txt" ]; then
    echo -e "${GREEN}✅${NC} requirements.txt present"
fi
if [ -f "$BAW_DIR/config.sample.yaml" ]; then
    echo -e "${GREEN}✅${NC} config.sample.yaml present"
fi

# ── Done ──
echo ""
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✅  BAW v0.10 installed successfully!${NC}"
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo ""
echo -e "  ${CYAN}1.${NC} Set your API keys:"
echo -e "     ${BOLD}echo 'DEEPSEEK_API_KEY=sk-your-key' >> ~/.baw/.env${NC}"
echo ""
echo -e "  ${CYAN}2.${NC} Make sure \"baw\" command works:"
echo -e "     ${BOLD}baw --version${NC}"
echo -e "     ${YELLOW}(If 'command not found', run the PATH command above first)${NC}"
echo ""
echo -e "  ${CYAN}3.${NC} Run the setup wizard:"
echo -e "     ${BOLD}baw --setup${NC}"
echo ""
echo -e "  ${CYAN}4.${NC} Try some commands:"
echo -e "     ${BOLD}baw --btw 'Hello BAW!'${NC}"
echo -e "     ${BOLD}baw --mode quick 'What time is it?'${NC}"
echo -e "     ${BOLD}baw --tone business 'Write a short proposal'${NC}"
echo -e "     ${BOLD}baw${NC}                        ${YELLOW}# Interactive chat mode${NC}"
echo ""
echo -e "  ${CYAN}5.${NC} Read the docs:"
echo -e "     https://cornreform.github.io/baw-agent-platform/"
echo ""
