#!/usr/bin/env bash
# BAW Installer — one-command setup
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/cornreform/baw-agent-platform/main/install.sh | bash
#   bash install.sh
#
# Supports: Bash, Zsh, Fish (auto-detected)

set -e

BAW_REPO="https://github.com/cornreform/baw-agent-platform.git"
BAW_DIR="$HOME/baw"
BAW_BIN_DIR="$HOME/.local/bin"
BAW_BIN="$BAW_BIN_DIR/baw"
PYTHON=""
SHELL_CONFIG=""

# ── Colours ──
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║     BAW — Black And White Agent      ║"
echo "  ║         One-Command Installer         ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${NC}"

# ── Find uv ──
if ! command -v uv &>/dev/null; then
    echo -e "${CYAN}⏳ uv not found — installing...${NC}"
    curl -LsSf https://astral.sh/uv/install.sh | bash
    # Source the newly installed uv for this session
    export PATH="$HOME/.local/bin:$PATH"
    if ! command -v uv &>/dev/null; then
        echo -e "${RED}❌ uv installation failed. Please install manually: https://docs.astral.sh/uv/${NC}"
        exit 1
    fi
    echo -e "${GREEN}✅${NC} uv installed: $(uv --version 2>&1)"
else
    echo -e "${GREEN}✅${NC} uv: $(uv --version 2>&1)"
fi

# ── Find Python ──
PYTHON=""
for py in $(uv python find 3.12 2>/dev/null) $(uv python find 3.11 2>/dev/null) python3.12 python3.11 python3; do
    if [ -x "$py" ] || command -v "$py" &>/dev/null; then
        PYTHON="$py"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo -e "${CYAN}⏳ Python 3.11+ not found — installing via uv...${NC}"
    uv python install 3.12
    PYTHON=$(uv python find 3.12)
    if [ -z "$PYTHON" ]; then
        echo -e "${RED}❌ Python installation failed.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✅${NC} Python installed: $($PYTHON --version 2>&1)"
else
    echo -e "${GREEN}✅${NC} Python: $($PYTHON --version 2>&1)"
fi

# ── Find Git ──
if ! command -v git &>/dev/null; then
    echo -e "${RED}❌ Git not found. Install it first.${NC}"
    exit 1
fi
echo -e "${GREEN}✅${NC} Git: $(git --version 2>&1)"

# ── Install dependencies with uv ──
echo ""
echo -e "${CYAN}📦 Installing Python dependencies...${NC}"
cd "$BAW_DIR" && uv pip install -r requirements.txt --system 2>&1 | tail -3
echo -e "${GREEN}✅${NC} Dependencies installed"

# ── Clone or update repo ──
echo ""
echo -e "${CYAN}📁 Setting up BAW repo...${NC}"
if [ -d "$BAW_DIR" ]; then
    echo "   BAW already exists at $BAW_DIR — pulling latest..."
    cd "$BAW_DIR" && git pull
else
    git clone "$BAW_REPO" "$BAW_DIR"
fi
echo -e "${GREEN}✅${NC} BAW repo ready at $BAW_DIR"

# ── Create CLI wrapper ──
mkdir -p "$BAW_BIN_DIR"
cat > "$BAW_BIN" << WRAPPER
#!/usr/bin/env bash
# BAW CLI wrapper — auto-generated by install.sh
cd "\$HOME/baw" && exec uv run python "\$HOME/baw/baw" "\$@"
WRAPPER
chmod +x "$BAW_BIN"
echo -e "${GREEN}✅${NC} CLI wrapper: $BAW_BIN"

# ── Detect shell and suggest PATH setup ──
echo ""
echo -e "${CYAN}🔧 Shell PATH setup...${NC}"

# Find the user's actual shell
SHELL_NAME="$(basename "$SHELL" 2>/dev/null || echo "bash")"
case "$SHELL_NAME" in
    zsh)
        SHELL_CONFIG="$HOME/.zshrc"
        PATH_CMD='export PATH="$HOME/.local/bin:$PATH"'
        ;;
    bash)
        SHELL_CONFIG="$HOME/.bashrc"
        PATH_CMD='export PATH="$HOME/.local/bin:$PATH"'
        ;;
    fish)
        SHELL_CONFIG="$HOME/.config/fish/config.fish"
        PATH_CMD='fish_add_path "$HOME/.local/bin"'
        ;;
    *)
        SHELL_CONFIG="$HOME/.profile"
        PATH_CMD='export PATH="$HOME/.local/bin:$PATH"'
        ;;
esac

if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
    echo -e "${GREEN}✅${NC} ~/.local/bin already in PATH"
else
    echo -e "  ${YELLOW}⚠️  ~/.local/bin is NOT in your PATH${NC}"
    echo ""
    if _confirm "Add ~/.local/bin to PATH automatically?"; then
        echo "$PATH_CMD" >> "$SHELL_CONFIG"
        echo -e "${GREEN}✅${NC} Added to $SHELL_CONFIG"
        echo -e "  ${YELLOW}Run: source $SHELL_CONFIG${NC} (or open a new terminal)"
        # Export for this session so verification works
        export PATH="$HOME/.local/bin:$PATH"
    else
        echo ""
        echo "   Add it manually by running:"
        echo -e "     ${BOLD}echo '$PATH_CMD' >> $SHELL_CONFIG${NC}"
        echo -e "     ${BOLD}source $SHELL_CONFIG${NC}"
        echo ""
    fi
    echo ""
fi

# ── Verify installation ──
echo ""
echo -e "${CYAN}🔍 Verifying installation...${NC}"
if [ -f "$BAW_BIN" ] && [ -x "$BAW_BIN" ]; then
    echo -e "${GREEN}✅${NC} CLI wrapper executable"
fi
if [ -d "$BAW_DIR/baw" ]; then
    echo -e "${GREEN}✅${NC} BAW source files present"
fi
if [ -f "$BAW_DIR/requirements.txt" ]; then
    echo -e "${GREEN}✅${NC} requirements.txt present"
fi
if [ -f "$BAW_DIR/config.sample.yaml" ]; then
    echo -e "${GREEN}✅${NC} config.sample.yaml present"
fi

# Run baw --version to confirm everything works
if command -v baw &>/dev/null; then
    echo ""
    baw --version
    echo ""
else
    echo -e "${YELLOW}⚠️  'baw' command not yet available in this session.${NC}"
    echo -e "   Run: ${BOLD}source $SHELL_CONFIG${NC} (or open a new terminal)"
    echo ""
fi

# ── Done ──
echo ""
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✅  BAW v0.20.1 installed successfully!${NC}"
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo ""
echo -e "  ${CYAN}1.${NC} Run the setup wizard:"
echo -e "     ${BOLD}baw --setup${NC}"
echo ""
echo -e "  ${CYAN}2.${NC} After setup, verify everything works:"
echo -e "     ${BOLD}baw --doctor${NC}"
echo ""
echo -e "  ${CYAN}3.${NC} Test the agent:"
echo -e "     ${BOLD}baw \"Hello BAW!\"${NC}"
echo ""
echo -e "  ${CYAN}4.${NC} Read the docs:"
echo -e "     ${BOLD}https://cornreform.github.io/baw-agent-platform/${NC}"
echo ""
