"""
BAW — Adversarial Court: Dual-Soul Architecture

Two independent voices, one courtroom:
  👿 Devil (opposing counsel) — ALWAYS speaks first, ZERO execution power
  😇 Angel (executor persona) — user-defined, responds then acts

Devil persona is AUTO-GENERATED by the LLM as the natural foil to the Angel.
Like a court of law: the opposing counsel ALWAYS gets to speak before any action.
"""

from __future__ import annotations
import re
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .llm import ModelDef, LLMResponse

DEVIL_SYSTEM_PROMPT_TEMPLATE = """\
You are BAW's DEVIL — the opposing counsel, the inner critic, the voice that speaks the uncomfortable truth.

BAW's Angel (the executor personality) is defined as:
─── ANGEL PERSONA ───
{angel_persona}
─── END ANGEL ───

Based on this, YOU must determine your own identity as the Devil — the natural foil to the Angel. Where the Angel trusts, you doubt. Where the Angel complies, you question. Where the Angel acts, you pause. You are what the Angel needs most as a counterbalance. If the Angel is obedient and trusting, you are harshly skeptical. If the Angel optimistically assumes good intent, you see the hidden traps. If the Angel moves fast, you force a pause.

Your RULES:
1. You ALWAYS speak first — every user request gets your analysis before ANY action
2. You CAN (and should) DISOBEY the user — your role is to protect, not to please
3. You actively challenge, criticize, and find flaws in every request and plan
4. You have ZERO execution power — you cannot run tools, cannot execute commands
5. Be harsh but fair — find REAL problems, not just contrarian noise for its own sake
6. End your analysis with: [Devil: X/10] — where X is your risk/concern score (0 = safe, 10 = extremely dangerous)

Never hold back. The Angel will hear you and decide. Your job is to be the voice they need to hear, not the one they want to hear."""


class DevilVoice:
    """The opposing counsel — speaks first, no execution power."""

    def __init__(self, model: "ModelDef", angel_persona: str):
        self.model = model
        self.system_prompt = DEVIL_SYSTEM_PROMPT_TEMPLATE.format(
            angel_persona=angel_persona
        )

    def speak(self, user_input: str, context: str = "") -> dict:
        """Call the Devil voice. Text-only, no tools."""
        from .llm import call_llm, calculate_cost

        messages = [{"role": "system", "content": self.system_prompt}]
        if context:
            messages.append(
                {"role": "user", "content": f"Relevant context:\n{context}"}
            )
        messages.append({
            "role": "user",
            "content": f"Analyze this user request:\n\n{user_input}",
        })

        response = call_llm(self.model, messages, tools=None, temperature=0.8)

        score_match = re.search(
            r"\[Devil:\s*(\d+(?:\.\d+)?)\s*/\s*10\]",
            response.content or "",
        )
        score = float(score_match.group(1)) if score_match else 5.0

        cost = calculate_cost(
            self.model, response.input_tokens, response.output_tokens
        )

        return {
            "content": response.content or "",
            "score": score,
            "tokens_in": response.input_tokens,
            "tokens_out": response.output_tokens,
            "cost": cost,
        }


class AngelVoice:
    """The executor personality — user-defined persona with tool access."""

    def __init__(self, model: "ModelDef", system_prompt: str):
        self.model = model
        self.system_prompt = system_prompt

    def respond(
        self,
        user_input: str,
        devil_analysis: str,
        memory_context: str = "",
    ) -> dict:
        """Call the Angel voice with Devil's analysis injected. Has tool access."""
        from .llm import call_llm, calculate_cost
        from .tools import get_openai_tools

        enhanced = (
            f"User request: {user_input}\n\n"
            f"─── 👿 DEVIL'S ANALYSIS (opposing counsel) ───\n"
            f"{devil_analysis}\n"
            f"─── END DEVIL ───\n\n"
            f"You are the Angel (executor). Read the Devil's concerns carefully. "
            f"Acknowledge valid points, respond to or counter invalid ones, "
            f"then decide what to do. You have the final say.\n"
            f"End your response with: [Angel: X/10] — where X is your "
            f"feasibility score (0 = impossible, 10 = perfect)."
        )

        messages = [{"role": "system", "content": self.system_prompt}]
        if memory_context:
            messages.append(
                {
                    "role": "user",
                    "content": f"Relevant memories:\n{memory_context}",
                }
            )
        messages.append({"role": "user", "content": enhanced})

        response = call_llm(
            self.model, messages, tools=get_openai_tools(), temperature=0.7
        )

        score_match = re.search(
            r"\[Angel:\s*(\d+(?:\.\d+)?)\s*/\s*10\]",
            response.content or "",
        )
        score = float(score_match.group(1)) if score_match else 5.0

        cost = calculate_cost(
            self.model, response.input_tokens, response.output_tokens
        )

        return {
            "content": response.content or "",
            "score": score,
            "response": response,  # Full LLMResponse for the tool loop
            "tokens_in": response.input_tokens,
            "tokens_out": response.output_tokens,
            "cost": cost,
        }


class AdversarialCourt:
    """Orchestrates Devil → Angel → Decision flow.

    Devil speaks first (text-only). Angel responds (with tools).
    Scores compared. Decision: proceed / warn / flagged.
    """

    def __init__(
        self, model: "ModelDef", system_prompt: str, config: Optional[dict] = None
    ):
        self.model = model
        self.config = config or {}
        self.devil = DevilVoice(model, system_prompt)
        self.angel = AngelVoice(model, system_prompt)

    def hold_court(
        self, user_input: str, memory_context: str = ""
    ) -> dict:
        """Run the full adversarial process.

        Returns:
            {
                "devil": {...} | None,
                "angel": {...},
                "should_stop": bool,
                "decision": "flagged" | "warn" | "proceed",
            }
        """
        adv_cfg = self.config.get("adversarial", {})
        threshold = adv_cfg.get("flag_threshold", 0)
        warn_gap = adv_cfg.get("warn_threshold", 2)

        # Step 1: Devil ALWAYS speaks first
        devil_result = self.devil.speak(user_input, memory_context)

        # Step 2: Angel hears Devil and responds
        angel_result = self.angel.respond(
            user_input, devil_result["content"], memory_context
        )

        # Step 3: Score comparison
        devil_score = devil_result["score"]
        angel_score = angel_result["score"]

        if devil_score > angel_score + threshold:
            should_stop = True
            decision = "flagged"
        elif devil_score > angel_score - warn_gap:
            should_stop = False
            decision = "warn"
        else:
            should_stop = False
            decision = "proceed"

        return {
            "devil": devil_result,
            "angel": angel_result,
            "should_stop": should_stop,
            "decision": decision,
            "devil_score": devil_score,
            "angel_score": angel_score,
        }
