"""BAW — Secure API Key Vault

Auto-backup and auto-restore for ~/.baw/.env API keys.

Three-layer protection:
  1. .env (primary) — read by all code, normal permissions
  2. Vault (backup)   — ~/.baw/key_vault/keys.json, chmod 600
  3. Emergency copy   — ~/.baw/key_vault/.env.emergency, chmod 400

On startup:
  - If .env ok → sync to vault (if vault missing/stale)
  - If .env empty → restore from vault
  - If both missing → log warning, do nothing
"""

import json
import logging
import os
import shutil
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("baw.key_vault")

VAULT_DIR = Path.home() / ".baw" / "key_vault"
VAULT_FILE = VAULT_DIR / "keys.json"
EMERGENCY_FILE = VAULT_DIR / ".env.emergency"
ENV_FILE = Path.home() / ".baw" / ".env"

REQUIRED_KEYS = [
    "DEEPSEEK_API_KEY",
    "MINIMAX_API_KEY",
    "MOONSHOT_API_KEY",
    "OPENROUTER_API_KEY",
    "STEPFUN_API_KEY",
    "XAI_API_KEY",
    "OPENAI_API_KEY",
    "AGNES_API_KEY",
    "FIRECRAWL_API_KEY",
]


def _ensure_vault_dir():
    VAULT_DIR.mkdir(parents=True, exist_ok=True)
    VAULT_DIR.chmod(0o700)  # only owner


def _read_env(path: Path) -> dict:
    """Read a .env file and return a dict of key->value pairs."""
    if not path.exists():
        return {}
    result = {}
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k:
                result[k] = v
    except Exception as e:
        logger.warning(f"[KeyVault] Could not read {path}: {e}")
    return result


def _write_env(path: Path, data: dict):
    """Write a dict of key->value pairs to a .env file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# BAW API Keys — auto-generated by key_vault", ""]
    for k in REQUIRED_KEYS:
        v = data.get(k)
        if v:
            lines.append(f"{k}={v}")
    # Also write any other keys not in REQUIRED_KEYS
    for k, v in data.items():
        if k not in REQUIRED_KEYS and v:
            lines.append(f"{k}={v}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(0o600)  # owner read/write only


def _load_vault() -> dict:
    """Load keys from vault storage. Returns {} if nothing available."""
    if VAULT_FILE.exists():
        try:
            return json.loads(VAULT_FILE.read_text(encoding="utf-8")).get("keys", {})
        except Exception:
            pass
    if EMERGENCY_FILE.exists():
        return _read_env(EMERGENCY_FILE)
    return {}


def backup():
    """Sync .env keys to vault storage.

    If .env is empty, auto-restore from vault.
    If vault is also empty, warn and skip.
    """
    env_data = _read_env(ENV_FILE)
    if not env_data:
        logger.warning("[KeyVault] .env is EMPTY — vault will still restore from last backup")
        vault_data = _load_vault()
        if vault_data:
            logger.warning("[KeyVault] .env was empty, but vault has keys. Attempting restore.")
            _write_env(ENV_FILE, vault_data)
            # Reload into current process env
            for k, v in vault_data.items():
                os.environ.setdefault(k, v)
            return
        return

    _ensure_vault_dir()

    # Write JSON vault (structured, readable by code)
    vault_data = {
        "version": 1,
        "backed_up_at": datetime.now().isoformat(),
        "keys": env_data,
    }
    VAULT_FILE.write_text(json.dumps(vault_data, indent=2), encoding="utf-8")
    VAULT_FILE.chmod(0o600)

    # Write emergency .env copy (readable by shell/env loader)
    _write_env(EMERGENCY_FILE, env_data)
    EMERGENCY_FILE.chmod(0o400)  # read-only by owner

    key_count = len([k for k in REQUIRED_KEYS if k in env_data])
    logger.info(f"[KeyVault] Backed up {key_count}/{len(REQUIRED_KEYS)} required keys")


def restore() -> int:
    """Restore .env from vault if .env is missing or empty.

    Returns: number of keys restored, or 0 if nothing needed.
    """
    env_data = _read_env(ENV_FILE)
    required_found = sum(1 for k in REQUIRED_KEYS if k in env_data)

    # If .env has all required keys, nothing to restore
    if required_found >= len(REQUIRED_KEYS):
        return 0

    # Try vault first
    vault_data = {}
    if VAULT_FILE.exists():
        try:
            vault_data = json.loads(VAULT_FILE.read_text(encoding="utf-8")).get("keys", {})
        except Exception:
            pass

    # Try emergency copy as fallback
    if not vault_data and EMERGENCY_FILE.exists():
        vault_data = _read_env(EMERGENCY_FILE)

    if not vault_data:
        logger.warning("[KeyVault] No backup found — cannot restore")
        return 0

    # Merge: keep existing keys, add missing from vault
    merged = dict(env_data)
    restored = 0
    for k in REQUIRED_KEYS:
        if k not in merged and k in vault_data:
            merged[k] = vault_data[k]
            restored += 1

    if restored > 0:
        _write_env(ENV_FILE, merged)
        logger.info(f"[KeyVault] Restored {restored} missing keys from vault")
        # Reload into current process env
        for k, v in merged.items():
            os.environ.setdefault(k, v)

    return restored


def verify() -> dict:
    """Check health of all key sources. Returns status dict.

    Keys are healthy when present in BOTH .env AND vault/emergency.
    If .env is missing keys but vault has them, restore is possible.
    """
    env_data = _read_env(ENV_FILE)
    vault_data = _load_vault()
    emerg_data = {}

    if not vault_data and EMERGENCY_FILE.exists():
        emerg_data = _read_env(EMERGENCY_FILE)

    status = {}
    for k in REQUIRED_KEYS:
        in_env = k in env_data
        status[k] = {
            "env": in_env,
            "vault": k in vault_data or k in emerg_data,
            "process": bool(os.environ.get(k, "")),
        }
    return status


def cron_health_check() -> str:
    """Run by cron job: check .env integrity, auto-restore if needed.

    Returns a report string (empty if healthy).
    """
    env_data = _read_env(ENV_FILE)
    missing = [k for k in REQUIRED_KEYS if k not in env_data]
    if not missing:
        # Sync vault on every check
        backup()
        return ""

    # Try restore
    vault_data = _load_vault()
    restored = 0
    for k in missing:
        if k in vault_data:
            env_data[k] = vault_data[k]
            restored += 1

    if restored > 0:
        _write_env(ENV_FILE, env_data)
        for k, v in env_data.items():
            os.environ.setdefault(k, v)
        return f"[KeyVault] Restored {restored}/{len(missing)} missing keys"

    return f"[ALERT] {len(missing)} keys missing from .env AND vault"
