"""BAW built-in: self_migrate — migrate BAW to a new machine.

Handles:
- Analyze target machine (OS, arch, resources)
- Generate migration script
- Data export (config, memory, sessions, SOUL)
- Bootstrap: clone repo → install deps → build → start
"""
import json
import os
import shutil
import subprocess
import sys
import tarfile
import time
from pathlib import Path
from datetime import datetime


_BAW_HOME = Path(os.environ.get("BAW_HOME", "/app"))
_BAW_DATA = Path(os.environ.get("BAW_RUNTIME_HOME", Path.home() / ".baw"))
_GIT_REPO = "https://github.com/cornreform/baw-agent-platform.git"


def _run(cmd: list[str], timeout: int = 30) -> dict:
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return {"ok": r.returncode == 0, "output": r.stdout.strip(), "error": r.stderr.strip() or None}
    except Exception as e:
        return {"ok": False, "output": "", "error": str(e)}


def _export_data(target_dir: Path) -> dict:
    """Export BAW data (config, memory, sessions, SOUL) to a tar.gz."""
    export_path = target_dir / f"baw-export-{datetime.now().strftime('%Y%m%d-%H%M%S')}.tar.gz"

    files_to_export = [
        _BAW_DATA / "config.yaml",
        _BAW_DATA / "SOUL.md",
        _BAW_DATA / "memory",
        _BAW_DATA / "sessions",
        _BAW_DATA / "cron" / "jobs.json",
        _BAW_DATA / "logs" / "tokens.jsonl",
    ]

    target_dir.mkdir(parents=True, exist_ok=True)
    with tarfile.open(export_path, "w:gz") as tar:
        for f in files_to_export:
            p = Path(f)
            if p.exists():
                tar.add(str(p), arcname=str(p.relative_to(_BAW_DATA)))

    if export_path.exists():
        return {"ok": True, "path": str(export_path), "size_kb": round(export_path.stat().st_size / 1024, 1)}
    return {"ok": False, "error": "Export file was not created"}


def _generate_bootstrap(target_dir: Path) -> dict:
    """Generate a bootstrap script for the target machine."""
    script = f"""#!/usr/bin/env bash
set -e

# BAW Self-Bootstrap Script
# Generated by BAW on {datetime.now().isoformat()}

echo "=== BAW Bootstrap ==="

# Check prerequisites
command -v python3 >/dev/null 2>&1 || {{ echo "ERROR: python3 required"; exit 1; }}
command -v git >/dev/null 2>&1 || {{ echo "ERROR: git required"; exit 1; }}
command -v docker >/dev/null 2>&1 || {{ echo "WARNING: docker not found — will install"; }}

# Clone repo
if [ ! -d baw-agent-platform ]; then
    echo "Cloning BAW repo..."
    git clone {_GIT_REPO}
fi
cd baw-agent-platform

# Copy exported data
echo "Restoring BAW data..."
mkdir -p ~/.baw
if [ -f {target_dir}/baw-export-*.tar.gz ]; then
    tar xzf {target_dir}/baw-export-*.tar.gz -C ~/.baw/
fi

# Copy .env if present
if [ -f {target_dir}/.env ]; then
    cp {target_dir}/.env ~/.baw/.env
fi

# Build and start
echo "Building BAW container..."
docker compose build baw-telegram
echo "Starting BAW..."
docker compose up -d baw-telegram

# Wait for health
for i in $(seq 1 15); do
    sleep 2
    HEALTH=$(docker inspect baw-telegram --format '{{{{.State.Health.Status}}}}' 2>/dev/null || echo "starting")
    if [ "$HEALTH" = "healthy" ]; then
        echo "BAW is running!"
        break
    fi
    echo "Waiting for BAW... ($i/15)"
done

echo "=== Bootstrap complete ==="
echo "BAW is running on this machine."
"""
    script_path = target_dir / "baw-bootstrap.sh"
    script_path.write_text(script)
    script_path.chmod(0o755)
    return {"ok": True, "path": str(script_path)}


def _analyze_target(host: str = "", username: str = "") -> dict:
    """Analyze target machine (or local environment)."""
    if host and username:
        # Remote analysis via SSH
        ssh_cmd = ["ssh", f"{username}@{host}"]
        checks = {
            "os": _run(ssh_cmd + ["cat", "/etc/os-release | head -3"]),
            "arch": _run(ssh_cmd + ["uname", "-m"]),
            "python": _run(ssh_cmd + ["python3", "--version"]),
            "docker": _run(ssh_cmd + ["docker", "--version"]),
            "git": _run(ssh_cmd + ["git", "--version"]),
            "memory": _run(ssh_cmd + ["free", "-h", "|", "head", "-2"]),
            "disk": _run(ssh_cmd + ["df", "-h", "/", "|", "tail", "-1"]),
        }
    else:
        # Local analysis
        checks = {
            "os": _run(["cat", "/etc/os-release"] if Path("/etc/os-release").exists() else ["uname", "-a"]),
            "arch": _run(["uname", "-m"]),
            "python": _run([sys.executable, "--version"]),
            "docker": _run(["docker", "--version"]),
            "git": _run(["git", "--version"]),
            "memory": _run(["free", "-h"]),
            "disk": _run(["df", "-h", "/"]),
        }

    result = {}
    for name, r in checks.items():
        result[name] = r["output"] if r["ok"] else r.get("error", "N/A")

    # Determine if target is suitable
    can_deploy = True
    if host:
        can_deploy = "docker" in result.get("docker", "") if result.get("docker") != "N/A" else False

    result["suitable"] = can_deploy
    return result


def _handler(
    action: str = "analyze",
    target_dir: str = "",
    host: str = "",
    username: str = "",
) -> str:
    """Prepare and execute BAW migration to a new machine.

    Supported actions:
      analyze     — Analyze target machine (local or remote via SSH)
      export      — Export BAW data (config, memory, sessions, SOUL)
      bootstrap   — Generate bootstrap script for new machine
      migrate     — Full: analyze → export → bootstrap (one command)
    """
    target = Path(target_dir) if target_dir else Path("/tmp/baw-migrate")
    if not target_dir:
        target = Path("/tmp/baw-migrate")

    actions = {
        "analyze": lambda: _analyze_target(host, username),
        "export": lambda: _export_data(target),
        "bootstrap": lambda: _generate_bootstrap(target),
        "migrate": lambda: _full_migrate(target, host, username),
    }

    handler = actions.get(action)
    if not handler:
        return json.dumps({"ok": False, "error": f"Unknown action: {action}"}, ensure_ascii=False)

    result = handler()
    return json.dumps(result, ensure_ascii=False, indent=2)


def _full_migrate(target_dir: Path, host: str, username: str) -> dict:
    """Run full migration: analyze → export → bootstrap."""
    steps = []

    # Step 1: Analyze
    analysis = _analyze_target(host, username)
    steps.append({"step": "analyze", "result": analysis})

    # Step 2: Export
    export = _export_data(target_dir)
    steps.append({"step": "export", "result": export})

    # Step 3: Bootstrap
    bootstrap = _generate_bootstrap(target_dir)
    steps.append({"step": "bootstrap", "result": bootstrap})

    return {"ok": True, "steps": steps,
            "instructions": (
                f"Migration package ready at: {target_dir}\n"
                f"1. Copy {target_dir} to the new machine\n"
                f"2. Run: bash {bootstrap.get('path', 'baw-bootstrap.sh')}\n"
                f"3. BAW will clone repo, restore data, build and start"
            )}


TOOL_DEF = {
    "name": "self_migrate",
    "description": (
        "[SELF-HOSTING] Migrate BAW to a new machine. "
        "Analyze target (local/remote), export data (config/memory/sessions/SOUL), "
        "generate bootstrap script, or run full migration pipeline. "
        "BAW can deploy itself to any Linux machine with Python + Docker."
    ),
    "handler": _handler,
    "parameters": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "enum": ["analyze", "export", "bootstrap", "migrate"],
                "description": "Migration action.",
                "default": "analyze",
            },
            "target_dir": {
                "type": "string",
                "description": "Directory to store export/bootstrap files (default: /tmp/baw-migrate).",
                "default": "",
            },
            "host": {
                "type": "string",
                "description": "Target hostname/IP for remote analysis (optional).",
                "default": "",
            },
            "username": {
                "type": "string",
                "description": "SSH username for remote analysis (optional).",
                "default": "",
            },
        },
        "required": [],
    },
    "risk_level": "high",
}
